### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by frankier** [koskenni/alignment#1]
Hi. Is this code freely licensed or "all rights reserved"?

**Comment by koskenni** [comment]
The code of aligner.py, charmetric.py and multialign.py is copyright by Kimmo Koskenniemi 2017 and is free software according to the GNU GPL 3 license. Added a mention to the README and will add the necessary text to the program files soon. The data file tyvebaas-n-aligned.text originates from data downloaded from open the web server Eesti Keele Instituut in Tallin. They may tell more about possible restrictions in using it.

**Comment by frankier** [comment]
Thanks!
